/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package webflux.junit5.test.app;

import webflux.junit5.test.list.LinkedList;

import static webflux.junit5.test.utilities.StringUtils.join;
import static webflux.junit5.test.utilities.StringUtils.split;
import static webflux.junit5.test.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
